# Form implementation generated from reading ui file 'C:\Users\Maks\pythonProject\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 641)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 551, 651))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 130, 255, 255), stop:0.55 rgba(175, 61, 235, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 10, 380, 46))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 511, 20))
        self.label_2.setObjectName("label_2")
        self.Key_text = QtWidgets.QLineEdit(self.widget)
        self.Key_text.setGeometry(QtCore.QRect(150, 140, 240, 40))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Key_text.setFont(font)
        self.Key_text.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color:#FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(34, 36, 44);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 250);\n"
"}")
        self.Key_text.setObjectName("Key_text")
        self.Img_text = QtWidgets.QLineEdit(self.widget)
        self.Img_text.setGeometry(QtCore.QRect(150, 190, 240, 40))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Img_text.setFont(font)
        self.Img_text.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color:#FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(34, 36, 44);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 250);\n"
"}")
        self.Img_text.setObjectName("Img_text")
        self.Text_text = QtWidgets.QLineEdit(self.widget)
        self.Text_text.setGeometry(QtCore.QRect(120, 330, 300, 220))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Text_text.setFont(font)
        self.Text_text.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color:#FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(34, 36, 44);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 250);\n"
"}")
        self.Text_text.setPlaceholderText("")
        self.Text_text.setObjectName("Text_text")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(210, 250, 121, 61))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    color:#FFF;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(34, 36, 44);\n"
"    border-bottom: 5px solid rgb(34, 36, 44);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 170, 250);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome to Azimuth"))
        self.label_2.setText(_translate("Form", "Shorthand is one of the methods of encoding textual information using special characters."))
        self.Key_text.setPlaceholderText(_translate("Form", "Enter Key..."))
        self.Img_text.setPlaceholderText(_translate("Form", "Enter Img..."))
        self.pushButton.setText(_translate("Form", "Push"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
